# Generated by Django 2.1.7 on 2019-03-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('classID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('teacher', models.CharField(max_length=30)),
                ('class_Name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
